### PR TITLE
Initial test

### PR DESCRIPTION
**Pull request by mwernimont**
Before making a pull request
----------------------------
First . . .
- [ ] Clean the code the way Vue likes it - run 'npm run lint --fix'        
- [x] Make sure all tests run

Then check for accessibly compliance
- [ ] Run WAVE plugin 508 compliance tool

Then run Browserstack; check that application works on . . .
- [x] Chrome
- [x] Safari
- [ ] Edge
- [x] Firefox
- [ ] Samsung Internet
- [ ] Internet Explorer 11 (not supported, but still needs at least a working user redirect page)

Finally . . .
- [ ] Update the changelog appropriately

Title
-----------
Brief description of changes. Reference the JIRA ticket if appropriate

Description
-----------
Fixing an issue where the map is overly large and the bar chart is overly small.

After making a pull request
---------------------------
- [ ] If appropriate, put the link to the PR in the ticket
- [x] Assign someone to review unless the change is trivial

### CODE REVIEW

**Comment by mwernimont** [comment]
@lindsayplatt so in the past the request was to have the map large and we didn't care about users having to scroll up and down.  So hopefully this fixes the super big and way too small issue, but feel like the need for the bar chart and map on the screen at the same time was not current request?  

I mean I had it in an older version where everything was on the screen at once, but that was usurped by bigger map wants from reviewers.

**Comment by lindsayplatt** [comment]
Hi Marty - I don't think having the bar & the map visible at the same time is what the issue is here. I was concerned that I couldn't see the map on one screen (I can't see the top of Maine and the bottom of Texas all at once right now). No matter how I scrolled, the map couldn't fit into one view on my laptop screen. I am fine with having to scroll further to see the chart, but I thought that we had set it up so the map was sized to be as big as I could be while still fitting on the screen.

**Comment by mwernimont** [comment]
For sure, so even with these changes you couldn't fit the map into your screen?

**Comment by lindsayplatt** [comment]
Oh sorry. Didn't pull these down to test yet. Was just responding to your comment and wanted to make sure we understood each other. Pulling down and testing now!

**Comment by mwernimont** [comment]
I got you, thanks for the clarification.  It does paint a clearer picture.

**Comment by lindsayplatt** [comment]
Tested this locally and it looks good on my laptop screen now!

**Review by lindsayplatt — APPROVED** [review]

**Pull request merged**
