### PR TITLE
Pointer for buttons and about this map edits

### PR DESCRIPTION
**Pull request by mwernimont**
Before making a pull request
----------------------------
First . . .
- [ ] Clean the code the way Vue likes it - run 'npm run lint --fix'        
- [x] Make sure all tests run

Then check for accessibly compliance
- [ ] Run WAVE plugin 508 compliance tool

Then run Browserstack; check that application works on . . .
- [x] Chrome
- [x] Safari
- [ ] Edge
- [x] Firefox
- [ ] Samsung Internet
- [ ] Internet Explorer 11 (not supported, but still needs at least a working user redirect page)

Finally . . .
- [ ] Update the changelog appropriately

Title
-----------
Brief description of changes. Reference the JIRA ticket if appropriate

Description
-----------
Water Use Parameter buttons get the pointer cursor.  Adjusted the About map text for water use and made it more opec? opace? Whatever less transparent. 

After making a pull request
---------------------------
- [ ] If appropriate, put the link to the PR in the ticket
- [x] Assign someone to review unless the change is trivial

### CODE REVIEW

**Comment by mwernimont** [comment]
^ Found the bar chart never highlighted if you left the waterUse page and came back, so set a function to fire everytime the page is mounted.

**Comment by mwernimont** [comment]
Hold off, I am introducing new bugs in my haste

**Comment by mwernimont** [comment]
@mhines-usgs should be good to go now when you gots the time

**Comment by mhines-usgs** [comment]
looks good to me, i too appreciate the more opaque about text, easier to read

**Review by mhines-usgs — APPROVED** [review]

**Pull request merged**
