### PR TITLE
Wbeep 119 map legend

### PR DESCRIPTION
**Pull request by abriggs-usgs**
Before making a pull request
----------------------------

- [x] Make sure all tests run (still no tests)
- [x] Update the changelog appropriately

WBEEP-119 Add Map Legend
-----------
Added Map Legend

Description
-----------
In the process of butting my head against the wall on a different but related ticket, I ended up completing this one while figuring out what was breaking the other one. 

Summary
Added a legend as a Vue component that will dynamically update if the HRU color array is changed in the style sheet. Also made some very minor cosmetic color changes. Switched the layer order so Canada and Mexico cover up the sloppy HRUs on the borders (felt this was okay, since the stated MVP is a map of the continental US), removed the USWDS 'selection' component (as we are not sure what we are doing with it) and changed the title to something closer to a 'beta' version of the title. The colors and title changes are merely suggestions for people to review.

After making a pull request
---------------------------
- [x] If appropriate, put the link to the PR in the ticket
- [x] Assign someone to review unless the change is trivial

### CODE REVIEW

**Comment by mwernimont** [comment]
I am not sure we want to be blocking the any of the HRU's from view, would think checking with Lindsay first is the thing to do before merging this.

**Comment by mwernimont** [comment]
@lindsayplatt We cool with HRU's being clean cut across the U.S. Borders or do we need to show the extending parts that spill over into Canada and Mexico?

**Comment by lindsayplatt** [comment]
I'm pretty sure they didn't want to show the ones that extended to Canada, so I think this is OK. Let me check, though!

**Comment by mwernimont** [comment]
Cool cool, good call then @abriggs-usgs, easy change if they change their minds anyway.

**Comment by mwernimont** [comment]
@lindsayplatt Do you have a better title for a quick change for Aaron to make?

**Comment by lindsayplatt** [comment]
@mwernimont he did change to something better in this PR https://github.com/usgs-makerspace/wbeep-viz/pull/51/files#diff-ea994a51b0d9884f4fc046eca11a5c99R5 👍 we will bring it up at the WAUSP demo later today and see if they can help us choose a good title

**Comment by abriggs-usgs** [comment]
I added a couple of hack changes to the CSS so that this would look okay to demonstrate on 'test.' We can revisit these later and find a perfect solution.

**Pull request merged**
