### PR TITLE
vertical yaxis label + centered x season labels

### PR DESCRIPTION
**Pull request by lindsayplatt**
image

### CODE REVIEW

**Comment by mwernimont** [comment]
@lindsayplatt now that is a thing of beauty!

**Comment by mwernimont** [comment]
Just have to wait for my PR to be merged, so it doesn't mess with this greatness.

**Comment by lindsayplatt** [comment]
Only other thing I am thinking about is whether we should add some actual months to this. Especially to help explain why winter exists twice.

**Comment by mwernimont** [comment]
If we could get it under the season labels that could work, as that December winter basically has no room to begin with to share horizontally.  If did the winters we would probs want to do all the season months for consistency.  Would April - June Be cool or do we have to list all the months?

**Comment by mwernimont** [comment]
My merge of my manual SVG changes was fudging things up, so I did the merge conflict changes.

**Pull request merged**
