### PR TITLE
Water temp legend

### PR DESCRIPTION
**Pull request by mwernimont**
Before making a pull request
----------------------------
First . . .
- [ ] Clean the code the way Vue likes it - run 'npm run lint --fix'        
- [x] Make sure all tests run

Then check for accessibly compliance
- [ ] Run WAVE plugin 508 compliance tool

Then run Browserstack; check that application works on . . .
- [x] Chrome
- [x] Safari
- [ ] Edge
- [x] Firefox
- [ ] Samsung Internet
- [ ] Internet Explorer 11 (not supported, but still needs at least a working user redirect page)

Finally . . .
- [ ] Update the changelog appropriately

Title
-----------
Brief description of changes. Reference the JIRA ticket if appropriate

Description
-----------
Added a dot and text to the legend

After making a pull request
---------------------------
- [ ] If appropriate, put the link to the PR in the ticket
- [x] Assign someone to review unless the change is trivial

### CODE REVIEW

**Comment by mwernimont** [comment]
Screen Shot 2020-12-02 at 9 50 28 AM

**Comment by mhines-usgs** [comment]
Any way to left justify everything? seems kinda weirdly aligned with the water temp legend bits?

**Comment by mwernimont** [comment]
Well it will look weird either way, since the usgs monitoring text is so much longer, so left justify the legend you get lots of right white space.  I personally don't care, so you can make the call.

**Comment by mwernimont** [comment]
Screen Shot 2020-12-02 at 10 04 57 AM

**Comment by mhines-usgs** [comment]
my eyes like that better, we can see what jen thinks once you merge it?

**Pull request merged**
