### PR TITLE
Water Use legends

### PR DESCRIPTION
**Pull request by mwernimont**
Before making a pull request
----------------------------
First . . .
- [ ] Clean the code the way Vue likes it - run 'npm run lint --fix'        
- [x] Make sure all tests run

Then check for accessibly compliance
- [ ] Run WAVE plugin 508 compliance tool

Then run Browserstack; check that application works on . . .
- [x] Chrome
- [x] Safari
- [ ] Edge
- [x] Firefox
- [ ] Samsung Internet
- [ ] Internet Explorer 11 (not supported, but still needs at least a working user redirect page)

Finally . . .
- [ ] Update the changelog appropriately

Title
-----------
Brief description of changes. Reference the JIRA ticket if appropriate

Description
-----------
Legends now have values, which are probably up for changes, but good to test currently

After making a pull request
---------------------------
- [ ] If appropriate, put the link to the PR in the ticket
- [x] Assign someone to review unless the change is trivial

### CODE REVIEW

**Comment by mwernimont** [comment]
@mhines-usgs mind taking some screen shots?  Want to see if the text looks consistent on others machines

**Comment by mhines-usgs** [comment]
i think the size of the legend looks good! 
i think we probably want to use the same abbreviation or try to make room for the full unit description (million gallons/day) somehow. (actually now that i look at it, it seems like the D is just cut off like the last comment I make here)
or maybe use mgd in the legend but underneath it in tiny text include mgd=million gallons/day?

there seems to be an issue with the text getting cut off in the svg of the seasonal bar chart - looks like it might need more room

image

**Comment by mwernimont** [comment]
Bleh, I expected it but was hoping it would just be easy.  You aren't getting my proposed text as your comp probs doesn't just have it sitting around.  Adjustments shall be made!

**Comment by mwernimont** [comment]
@mhines-usgs lets see if that fixes the text issue.  Also added your good idea of the unit explanation

**Comment by mhines-usgs** [comment]
that looks great!

**Pull request merged**
