### PR TITLE
update irrigation maps & data based on changes Amy talked about

### PR DESCRIPTION
**Pull request by lindsayplatt**
The irrigation data changed a bit, so Amy Puls asked me to update the water use figures for irrigation. @jenniferRapp has OK'ed this update prior to the release, but let's just double check it all on test just in case. I had no issues pulling the new data and running the code, so I think it should be OK.

### CODE REVIEW

**Comment by mhines-usgs** [comment]
seems ok to me!

**Review by mhines-usgs — APPROVED** [review]

**Comment by jenniferRapp** [comment]
What is the best way to compare ?  QA to the production version?

Jen

Jennifer L. Rapp, Physical Scientist
Chief, Decision Support Branch
USGS Water Mission Area
Richmond, VA 23228
804-615-6868 (mobile and home office)
jrapp@usgs.gov<mailto:jrapp@usgs.gov>

**Comment by lindsayplatt** [comment]
@jenniferRapp yes, that would be the best place to see before/after. As Amy noted in that email, the changes will be very small.

**Comment by jenniferRapp** [comment]
@lindsayplatt @mhines-usgs I see differences, increases in the amount of irrigation, especially during summer.  California near the Central Valley has bigger circles and looks like a larger 'blob', some of the circles in the Northern part of Idaho are larger than they were, New England Cape Cod is larger.  The thing that stands out to me is that the bar chart max changed from 447,000 to 611,000 mgd in this new version.     The actual shape of the bar chart changed too.  It is steeper in spring and summer in the new QA version. The patterns are the same, so it's really the magnitudes that appear to have increased, and how they account for the daily values changed a bit too.  I'd like to send this image out to Rich Niswonger to make sure he understands the changes.  
WU_irrigationUpdateCompare

**Pull request merged**
