### PR TITLE
add new sections for water use and water temp to q and a page

### PR DESCRIPTION
**Pull request by mhines-usgs**
Before making a pull request
----------------------------
First . . .
- [ ] Clean the code the way Vue likes it - run 'npm run lint --fix'        
- [ ] Make sure all tests run

Then check for accessibly compliance
- [ ] Run WAVE plugin 508 compliance tool

Then run Browserstack; check that application works on . . .
- [ ] Chrome
- [ ] Safari
- [ ] Edge
- [ ] Firefox
- [ ] Samsung Internet
- [ ] Internet Explorer 11 (not supported, but still needs at least a working user redirect page)

Finally . . .
- [ ] Update the changelog appropriately

Title
-----------
Add to the questionsAndAnswers page sections for water temperature and water use

Description
-----------
https://github.com/usgs-makerspace/makerspace-sandbox/issues/622
https://github.com/usgs-makerspace/makerspace-sandbox/issues/620

After making a pull request
---------------------------
- [ ] If appropriate, put the link to the PR in the ticket
- [ ] Assign someone to review unless the change is trivial

### CODE REVIEW

**Review by mwernimont — APPROVED** [review]

**Comment by mhines-usgs** [comment]
this adds the content but what is missing is a way to either link to a specific section within the page (e.g. would be nice to go right to the section for water temperature or water use down below water storage. And all the 'back to the map' buttons are just going back to / which is water storage in our routing.

we could instead use the router to decide what to show? e.g. instead of showing everything for water use, water temp and water storage maybe check to see where they came from and then only show the relevant section? i'm not entirely sure that's possible but it seems like something we might be able to do

**Comment by amrhoades** [comment]
@mhines-usgs Should we create a new issue to tackle those questions or log them on this issue? 

1.) Route user to appropriate QA section. I like what you suggested: use the router to decide what to show (would it jump to that section in the QA or hide the other sections?)
2. Back to the map buttons updated to route to map associate with section

**Comment by mhines-usgs** [comment]
@amrhoades Marty's already looking into it! Thanks!

**Comment by mhines-usgs** [comment]
@amrhoades -- achieved in PR https://github.com/usgs-makerspace/wbeep-viz/pull/479 - now merged and on test

**Pull request merged**
