### PR TITLE
Water Use Legend Adjustments

### PR DESCRIPTION
**Pull request by mwernimont**
Before making a pull request
----------------------------
First . . .
- [ ] Clean the code the way Vue likes it - run 'npm run lint --fix'        
- [x] Make sure all tests run

Then check for accessibly compliance
- [ ] Run WAVE plugin 508 compliance tool

Then run Browserstack; check that application works on . . .
- [x] Chrome
- [x] Safari
- [ ] Edge
- [x] Firefox
- [ ] Samsung Internet
- [ ] Internet Explorer 11 (not supported, but still needs at least a working user redirect page)

Finally . . .
- [ ] Update the changelog appropriately

Title
-----------
Brief description of changes. Reference the JIRA ticket if appropriate

Description
-----------
Added a middle circle and removed the MGD from the numbers as it was cluttering.  Would love your feedback and thoughts though @mhines-usgs 

After making a pull request
---------------------------
- [ ] If appropriate, put the link to the PR in the ticket
- [x] Assign someone to review unless the change is trivial

### CODE REVIEW

**Comment by mhines-usgs** [comment]
nice, I think this looks really good. I like dropping the need to explain the units by dropping the abbreviation altogether and just including the full description 👍  

unrelated to the approval of this work, is there any way to know the size of the circles to include those sizes in the legend too? meaning if I shrink my view down using the device switcher in firefox, for example, could we correlate the size of the circles in the legend to what we see in the actual map? 

image

**Review by mhines-usgs — APPROVED** [review]

**Comment by mwernimont** [comment]
I honestly don't know how we would do that currently.  As I feel like like it would be pretty complicated?  I was hoping we could strike a happy medium somehow where we are getting a point across, but maybe not matching exactly?

**Comment by mhines-usgs** [comment]
yeah, i know it would be complicated. maybe we could recommend it as a future goal if the product ever goes over into the enterprise development team.

**Comment by mwernimont** [comment]
The ol dreambook

**Comment by jenniferRapp** [comment]
I'm not seeing these issues in the git hub dashboard, so I missed this convo.  Lets talk in the call today.

**Pull request merged**
